#!/usr/bin/env bash
tar xvf /home/tu-wan/windows4t/dataset/UCF_Crime/denseflow/Training_Normal_Videos_Anomaly/Normal_Videos633_x264/flow_y.tar -C /home/tu-wan/windowswan/dataset/UCF_Crime/denseflow_img_6250/Training_Normal_Videos_Anomaly/Normal_Videos633_x264/flow_y
tar xvf /home/tu-wan/windows4t/dataset/UCF_Crime/denseflow/Training_Normal_Videos_Anomaly/Normal_Videos633_x264/flow_x.tar -C /home/tu-wan/windowswan/dataset/UCF_Crime/denseflow_img_6250/Training_Normal_Videos_Anomaly/Normal_Videos633_x264/flow_x
tar xvf /home/tu-wan/windows4t/dataset/UCF_Crime/denseflow/Training_Normal_Videos_Anomaly/Normal_Videos331_x264/flow_x.tar -C /home/tu-wan/windowswan/dataset/UCF_Crime/denseflow_img_6250/Training_Normal_Videos_Anomaly/Normal_Videos331_x264/flow_x
tar xvf /home/tu-wan/windows4t/dataset/UCF_Crime/denseflow/Training_Normal_Videos_Anomaly/Normal_Videos331_x264/flow_y.tar -C /home/tu-wan/windowswan/dataset/UCF_Crime/denseflow_img_6250/Training_Normal_Videos_Anomaly/Normal_Videos331_x264/flow_y
tar xvf /home/tu-wan/windows4t/dataset/UCF_Crime/denseflow/Training_Normal_Videos_Anomaly/Normal_Videos633_x264/img.tar -C /home/tu-wan/windowswan/dataset/UCF_Crime/denseflow_img_6250/Training_Normal_Videos_Anomaly/Normal_Videos633_x264/img
tar xvf /home/tu-wan/windows4t/dataset/UCF_Crime/denseflow/Training_Normal_Videos_Anomaly/Normal_Videos547_x264/flow_x.tar -C /home/tu-wan/windowswan/dataset/UCF_Crime/denseflow_img_6250/Training_Normal_Videos_Anomaly/Normal_Videos547_x264/flow_x
tar xvf /home/tu-wan/windows4t/dataset/UCF_Crime/denseflow/Training_Normal_Videos_Anomaly/Normal_Videos547_x264/flow_y.tar -C /home/tu-wan/windowswan/dataset/UCF_Crime/denseflow_img_6250/Training_Normal_Videos_Anomaly/Normal_Videos547_x264/flow_y
tar xvf /home/tu-wan/windows4t/dataset/UCF_Crime/denseflow/Training_Normal_Videos_Anomaly/Normal_Videos547_x264/img.tar -C /home/tu-wan/windowswan/dataset/UCF_Crime/denseflow_img_6250/Training_Normal_Videos_Anomaly/Normal_Videos547_x264/img
tar xvf /home/tu-wan/windows4t/dataset/UCF_Crime/denseflow/Training_Normal_Videos_Anomaly/Normal_Videos331_x264/img.tar -C /home/tu-wan/windowswan/dataset/UCF_Crime/denseflow_img_6250/Training_Normal_Videos_Anomaly/Normal_Videos331_x264/img
tar xvf /home/tu-wan/windows4t/dataset/UCF_Crime/denseflow/Training_Normal_Videos_Anomaly/Normal_Videos308_x264/flow_x.tar -C /home/tu-wan/windowswan/dataset/UCF_Crime/denseflow_img_6250/Training_Normal_Videos_Anomaly/Normal_Videos308_x264/flow_x
tar xvf /home/tu-wan/windows4t/dataset/UCF_Crime/denseflow/Training_Normal_Videos_Anomaly/Normal_Videos307_x264/img.tar -C /home/tu-wan/windowswan/dataset/UCF_Crime/denseflow_img_6250/Training_Normal_Videos_Anomaly/Normal_Videos307_x264/img
tar xvf /home/tu-wan/windows4t/dataset/UCF_Crime/denseflow/Training_Normal_Videos_Anomaly/Normal_Videos308_x264/flow_y.tar -C /home/tu-wan/windowswan/dataset/UCF_Crime/denseflow_img_6250/Training_Normal_Videos_Anomaly/Normal_Videos308_x264/flow_y
tar xvf /home/tu-wan/windows4t/dataset/UCF_Crime/denseflow/Training_Normal_Videos_Anomaly/Normal_Videos308_x264/img.tar -C /home/tu-wan/windowswan/dataset/UCF_Crime/denseflow_img_6250/Training_Normal_Videos_Anomaly/Normal_Videos308_x264/img
